### PR TITLE
Switch to Redox-compatible termion

### PR DESCRIPTION
**Pull request by jackpot51**
Pending the merge of https://github.com/ticki/termion/pull/25, I have changes in my fork that allow compilation of termion on Redox

### CODE REVIEW

**Comment by MovingtoMars** [comment]
I merged, but is this still necessary?

**Comment by jackpot51** [comment]
No, ticki has merged the fix on upstream termion

**Comment by MovingtoMars** [comment]
Ok then, I changed it back.

**Comment by jackpot51** [comment]
The bugs were in the Redox kernel and have been fixed. Sorry to make you go back and forth, now you can use ticki's termion

**Pull request merged**
