### PR TITLE
Add Alt-f/Alt-b emacs keybindings to move one word forwards/backwards

### PR DESCRIPTION
**Pull request by pengowen123**
Works the same as in bash.

### CODE REVIEW

**Comment by mmstick** [comment]
I'd like to see Ctrl-Left and Ctrl+Right implemented too. This PR looks good to me.

@MovingtoMars The PR I submitted earlier fixes the error that also happens in this PR, so once my PR is merged the error won't happen on this PR.

**Comment by MovingtoMars** [comment]
Just had a look at the code.

The problem with this PR is that it doesn't use the `word_divider_fn` from the Context, so the user can't change how words are defined.

Have a look at `fn get_word_before_cursor(&self, ignore_space_before_cursor: bool) -> Option<(usize, usize)>` in editor.rs.

**Comment by MovingtoMars** [comment]
Just had a look at the code.

The problem with this PR is that it doesn't use the `word_divider_fn` from the Context, so the user can't change how words are defined.

Have a look at `fn get_word_before_cursor(&self, ignore_space_before_cursor: bool) -> Option<(usize, usize)>` in editor.rs.

**Comment by pengowen123** [comment]
I rewrote the new function to use `Editor::get_words_and_cursor_position`, which internally uses `word_divider_fn`.

@mmstick I'm not sure how I should implement arrow keys. The current `Key` type doesn't support handling the control key with anything other than characters. I will take a look at adding that support soon.

**Comment by mmstick** [comment]
@pengowen123 Seems that would be entirely dependent upon https://github.com/ticki/termion/issues/46

**Comment by pengowen123** [comment]
In that case, I guess that feature will have to wait. If there aren't any other issues with this PR, I can squash the commits.

**Comment by MovingtoMars** [comment]
Hmm, I think it's fine right now. I'll make an issue for the ctrl+arrow keys.

**Pull request merged**
